# Generated by Django 5.1.1 on 2024-10-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='uuid',
        ),
    ]
