name: workflows

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  run-test:
    uses: ./.github/workflows/run-test.yml
  dev-build:
    if: ${{github.ref== 'dev'}}
    needs: run-test
    uses: ./.github/workflows/dev.build.yml
