name: workflows

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-workflow-run-test:
    uses: ./.github/workflows/run_test.yml
  call-workflow-dev-build:
    needs: call-workflow-run-test
    uses: ./.github/workflows/dev.build.yml
